###
POST http://localhost:8080/comment/create/post/22
Content-Type: application/json

{
  "text": "Male bahti tupiq post"

}
###
GET http://localhost:8080/comment/22
###

POST http://localhost:8080/comments/24/like
###
POST http://localhost:8080/comments/23/dislike
###
POST http://localhost:8080/comments/2/undoDislike