###
GET http://localhost:8080/post/3
###
POST http://localhost:8080/post/create
Content-Type: application/json

{
  "description":"",
  "postCategory": 3,
  "latitude":"42.830459",
  "longitude": "22.641374",
  "createdAt": "2022-02-02",
  "title": "Mnogo qk proekt.Zavijdaite"
}
###
DELETE http://localhost:8080/delete/1
###
POST http://localhost:8080/post/1/edit
Content-Type: application/json

{
  "description":"acascascas",
  "postCategory": 3,
  "latitude":"212312",
  "longitude": "12312",
  "createdAt": "2022-02-02",
  "title": "she mu eba malallalalalalalaaiakata"
}
###
POST http://localhost:8080/posts/3/like
###
POST http://localhost:8080/posts/3/undoLike
###
POST http://localhost:8080/posts/3/dislike
###
POST http://localhost:8080/posts/3/undoDislike
###
GET http://localhost:8080/posts/newsfeed
###
GET http://localhost:8080/posts/newsfeed/category
###
GET http://localhost:8080/posts/newsfeed/date
###
GET http://localhost:8080/posts/newsfeed/like
###
GET http://localhost:8080/posts/allForeignPosts
###
GET http://localhost:8080/posts/allForeignPosts/date
###
GET http://localhost:8080/posts/allForeignPosts/like
###
GET http://localhost:8080/post/3/location


