### //Get User with id = 1
GET http://localhost:8080/users/1
### //Get User with id = 2
GET http://localhost:8080/users/2
### //Get User with id = 3
GET http://localhost:8080/users/3
### //Get User with id = 4
GET http://localhost:8080/users/4
### //Get User with id = 10
GET http://localhost:8080/users/10
### //Get User with id = 11
GET http://localhost:8080/users/11

### //Get User with username = palakarski1/EXIST
GET http://localhost:8080/users/find/palakarski1
### //Get User with username = palakarsk2/EXIST
GET http://localhost:8080/users/find/palakarski2
### //Get User with username = palakarsk3/EXIST
GET http://localhost:8080/users/find/palakarski3
### //Get User with username = palakarsk4/EXIST
GET http://localhost:8080/users/find/palakarski4
### //Get User with username = palakarsk5/EXIST
GET http://localhost:8080/users/find/palakarski5
### //Get User with username = palakarsk6/NOT EXIST
GET http://localhost:8080/users/find/palakarski6
### //Get User with username = palakarsk7/NOT EXIST
GET http://localhost:8080/users/find/palakarski7
### //Get User with username = palakarsk8/NOT EXIST
GET http://localhost:8080/users/find/palakarski8


### //Valid Registration
POST http://localhost:8080/register
Content-Type: application/json

http://localhost:8080/register
### //Valid Registration
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstName":"Alex",
  "lastName":"Rangelov",
  "username":"palakarski2",
  "birthDate":"1993-02-22",
  "email":"palakarski2@mail.bg",
  "password":":@L#:!LKP",
  "confpassword":":@L#:!LKP",
  "createdAt":"1993-02-22T00:00:00",
  "admin":true
}
### //Valid Registration
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstName":"Alex",
  "lastName":"Rangelov",
  "username":"palakarski3",
  "birthDate":"1993-02-22",
  "email":"palakarski3",
  "password":"palakarski3@",
  "confpassword":"palakarski3@",
  "createdAt":"1993-02-22T00:00:00",
  "admin":true
}
### //Valid Registration
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstName":"Alex",
  "lastName":"Rangelov",
  "username":"palakarski4",
  "birthDate":"1993-02-22",
  "email":"palakarski4",
  "password":"palakarski4@",
  "confpassword":"palakarski4@",
  "createdAt":"1993-02-22T00:00:00",
  "admin":true
}
### //Valid Registration
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstName":"Alex",
  "lastName":"Rangelov",
  "username":"palakarskai5a3s2s21",
  "birthDate":"1993-02-22",
  "email":"palakarskia5@сsadddda",
  "password":"palakarski5@",
  "confpassword":"palakarski5@",
  "createdAt":"1993-02-22T00:00:00",
  "admin":false
}
### //Unvalid Registration ВАЖНООООО Internal Server Eror няма име
POST http://localhost:8080/register
Content-Type: application/json

{

  "lastName":"Rangelov",
  "username":"palakarski312",
  "birthDate":"1993-02-22",
  "email":"palakarsk1i32@mail.bg",
  "password":"palakarski3@",
  "confpassword":"palakarski3@",
  "createdAt":"1993-02-22T00:00:00",
  "admin":true
}
### //Unvalid Registration
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstName":"Alex",
  "lastName":"",
  "username":"palakarsk2222222",
  "birthDate":"1993-02-22",
  "email":"palakarsk2222i99999@gmail.com",
  "password":"palakarski4@",
  "confpassword":"palakarski4@",
  "createdAt":"1993-02-22T00:00:00",
  "admin":true

}
### //Unvalid Registration
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstName":"Alex",
  "lastName":"Rangelov",
  "username":"palakarski42",
  "birthDate":"1993-02-22",
  "email":"palakarski@gmail.com",
  "password":"palakarski4@",
  "confpassword":"palakarski4@",
  "createdAt":"1993-02-22T00:00:00",
  "admin":true
}
### //Unvalid Registration
POST http://localhost:8080/register
Content-Type: application/json

{
  "firstName":"Alex",
  "lastName":"Rangelov",
  "username":"palakarski5",
  "birthDate":"1993-02-22",
  "email":"palakarski@mail.com",
  "password":"palakarski5@",
  "confpassword":"palakarski5@",
  "createdAt":"1993-02-22T00:00:00",
  "admin":true
}
###
POST http://localhost:8080/login
Content-Type: application/json

{

"username":"palakarski2",
"password":"palakarski1@"

}
###
POST http://localhost:8080/login
Content-Type: application/json

{

  "username":"palakarski2",
  "password":":@L#:!LKP"

}

###
POST http://localhost:8080/logout
Content-Type: application/json

{
  "id" : 5,
  "firstName":"Alex",
  "lastName":"Rangelov",
  "username":"palakarski122345",
  "birthDate":"1993-02-22",
  "email":"palakarski1234256",
  "password":"12345678Ar!@",
  "createdAt":"1993-02-22T00:00:00",
  "isAdmin":false,
  "gender":"f"
}
###
PUT http://localhost:8080/changepass
Content-Type: application/json

{
  "oldpassword" : ":@L#:!LKP",
  "newpassword" : "palakarski1@",
  "confnewpassword" : "palakarski1@"

}

###
PUT http://localhost:8080/forgotten_password
Content-Type: application/json

{
  "email" : "palakarski1234256",
  "newpassword" : "12345678Ar!@12",
  "confnewpassword" : "12345678Ar!@12"

}

###
DELETE http://localhost:8080/delete

###
POST http://localhost:8080/user/1/follow
###
POST http://localhost:8080/user/5/follow

###
POST http://localhost:8080/user/3/unfollow

